cl /c /nologo /Od /EHsc /constexpr:depth2048 /MP8 /Icore /I%VK_SDK_PATH%\Include ^
/Yu"pch.h" ^
/Fp"projects\vs\x64\Debug\magma.pch" ^
/Fo"projects\vs\x64\Debug\" ^
magma.cpp ^
allocator\alignedAllocator.cpp ^
allocator\allocationCallbacks.cpp ^
allocator\cxxAllocator.cpp ^
allocator\deviceMemoryAllocator.cpp ^
auxiliary\accumulationBuffer.cpp ^
auxiliary\baseFramebuffer.cpp ^
auxiliary\blitRectangle.cpp ^
auxiliary\colorFramebuffer.cpp ^
auxiliary\colorMultisampleFramebuffer.cpp ^
auxiliary\depthFramebuffer.cpp ^
auxiliary\fillRectangleVertexShader.cpp ^
auxiliary\frameGrabber.cpp ^
auxiliary\generateMipmap.cpp ^
auxiliary\graphicsPipelineCache.cpp ^
auxiliary\imageDescriptorSet.cpp ^
auxiliary\immediateRender.cpp ^
auxiliary\multiAttachmentFramebuffer.cpp ^
auxiliary\profiler.cpp ^
auxiliary\sprite.cpp ^
auxiliary\swapchainFramebuffer.cpp ^
auxiliary\textShader.cpp ^
barriers\bufferMemoryBarrier.cpp ^
barriers\imageMemoryBarrier.cpp ^
core\pch.cpp ^
descriptors\binding.cpp ^
descriptors\bindingArray.cpp ^
descriptors\subpass.cpp ^
exceptions\exception.cpp ^
extensions\extensions.cpp ^
extensions\instanceExtensions.cpp ^
extensions\instanceLayers.cpp ^
extensions\layers.cpp ^
extensions\physicalDeviceExtensions.cpp ^
helpers\checkFeatureSupport.cpp ^
helpers\executeCommandBuffer.cpp ^
helpers\executeDeferredOperation.cpp ^
helpers\stringize.cpp ^
misc\deviceFaultInfo.cpp ^
misc\deviceQueueDescriptor.cpp ^
misc\format.cpp ^
misc\framebufferAttachmentImage.cpp ^
misc\geometry.cpp ^
misc\pipelineExecutable.cpp ^
misc\scopedDebugMarker.cpp ^
misc\sharing.cpp ^
misc\structureChain.cpp ^
objects\accelerationStructure.cpp ^
objects\accelerationStructureInstanceBuffer.cpp ^
objects\buffer.cpp ^
objects\bufferView.cpp ^
objects\commandBuffer.cpp ^
objects\commandBufferDebug.cpp ^
objects\commandPool.cpp ^
objects\computePipeline.cpp ^
objects\computePipelines.cpp ^
objects\conditionalRenderingBuffer.cpp ^
objects\debugReportCallback.cpp ^
objects\debugUtilsMessenger.cpp ^
objects\deferredOperation.cpp ^
objects\descriptorPool.cpp ^
objects\descriptorSet.cpp ^
objects\descriptorSetLayout.cpp ^
objects\device.cpp ^
objects\deviceMemory.cpp ^
objects\display.cpp ^
objects\displayMode.cpp ^
objects\dstTransferBuffer.cpp ^
objects\event.cpp ^
objects\fence.cpp ^
objects\fragmentDensityMap.cpp ^
objects\fragmentDensityMapView.cpp ^
objects\fragmentShadingRateAttachment.cpp ^
objects\framebuffer.cpp ^
objects\fullScreenExclusiveSwapchain.cpp ^
objects\graphicsPipeline.cpp ^
objects\graphicsPipelines.cpp ^
objects\image.cpp ^
objects\image1D.cpp ^
objects\image1DArray.cpp ^
objects\image2D.cpp ^
objects\image2DArray.cpp ^
objects\image2DAttachment.cpp ^
objects\image3D.cpp ^
objects\imageCube.cpp ^
objects\imagelessFramebuffer.cpp ^
objects\imageView.cpp ^
objects\indexBuffer.cpp ^
objects\indirectBuffer.cpp ^
objects\instance.cpp ^
objects\mutableImage.cpp ^
objects\mutableImageView.cpp ^
objects\object.cpp ^
objects\physicalDevice.cpp ^
objects\physicalDeviceGroup.cpp ^
objects\pipeline.cpp ^
objects\pipelineCache.cpp ^
objects\pipelineLayout.cpp ^
objects\primaryCommandBuffer.cpp ^
objects\queryPool.cpp ^
objects\queue.cpp ^
objects\rayTracingBuffer.cpp ^
objects\rayTracingPipeline.cpp ^
objects\rayTracingPipelines.cpp ^
objects\renderPass.cpp ^
objects\renderPassMultiview.cpp ^
objects\resource.cpp ^
objects\resourcePool.cpp ^
objects\sampler.cpp ^
objects\samplerYcbcrConversion.cpp ^
objects\semaphore.cpp ^
objects\shaderModule.cpp ^
objects\srcTransferBuffer.cpp ^
objects\storageBuffer.cpp ^
objects\storageTexelBuffer.cpp ^
objects\surface.cpp ^
objects\swapchain.cpp ^
objects\swapchainImage.cpp ^
objects\timelineSemaphore.cpp ^
objects\transformFeedbackBuffer.cpp ^
objects\uniformTexelBuffer.cpp ^
objects\validationCache.cpp ^
objects\vertexBuffer.cpp ^
shaders\pipelineShaderStage.cpp ^
shaders\rayTracingShaderGroup.cpp ^
shaders\shaderBindingTable.cpp ^
shaders\shaderReflection.cpp ^
shaders\specialization.cpp ^
states\colorBlendState.cpp ^
states\colorBlendStateAdvanced.cpp ^
states\multisampleState.cpp ^
states\multiViewportState.cpp ^
states\rasterizationState.cpp ^
states\vertexInputState.cpp ^
states\vertexInputStructure.cpp ^
states\viewportState.cpp ^
"third-party"\SPIRV-Reflect\spirv_reflect.c

lib /nologo /out:magma.lib ^
magma.obj ^
alignedAllocator.obj ^
allocationCallbacks.obj ^
cxxAllocator.obj ^
deviceMemoryAllocator.obj ^